version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5001:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "81:80"